apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "70"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  # zen:
  #   serviceInstanceName: iaf-zen-cpdservice
  #   serviceNamespace: ''
  serviceContinuity:
    continuousAnalyticsCorrelation: false
    isBackupDeployment: false
  ldap:
    port: '3389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '3636'
    url: 'ldap://localhost:3389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: {{.Values.spec.storageClass}}
  backupRestore:
    enableAnalyticsBackups: false 
  postgresql:
    backups:
      data:
        compression: gzip
        encryption: default
        jobs: 1
      endpointCA: {}
      onetimeBackup: {}
      retentionPolicy: 12m
      s3Credentials:
        keyNameAccessKeyID: AWS_ACCESS_KEY_ID
        keyNameAccessSecretKey: AWS_SECRET_ACCESS_KEY
        secretName: ceph-bucket
      scheduledBackup:
        backupOwnerReference: none
        immediate: true
        schedule: 0 0 0 * * *
      wal:
        compression: gzip
        encryption: default
        walMaxParallel: 1
    bootstrap:
      s3Credentials:
        keyNameAccessKeyID: AWS_ACCESS_KEY_ID
        keyNameAccessSecretKey: AWS_SECRET_ACCESS_KEY
        secretName: ceph-bucket
      wal:
        compression: gzip
        encryption: default
        walMaxParallel: 1
    edbPostgresSubscriptionName: cloud-native-postgresql-catalog-subscription
    parameters: {}
    replication: {}
    resources:
      limitsCPU: '1'
      limitsMemory: 1Gi
      requestsCPU: 500m
      requestsMemory: 1Gi
  topology:
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    iafCartridgeRequirementsName: ''
    netDisco: false
    observers:
      docker: false
      taddm: true
      servicenow: true
      ibmcloud: false
      alm: false
      viptela: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      hpnfvd: false
      ciscoaci: false
      azure: false
      rancher: true
      newrelic: false
      vmvcenter: true
      rest: true
      appdynamics: true
      jenkins: true
      zabbix: false
      bigcloudfabric: false
      file: true
      googlecloud: true
      dynatrace: true
      aws: false
      openstack: false
      vmwarensx: true
    storageClassElasticTopology: {{.Values.spec.storageClass}}
    storageClassFileObserver: {{.Values.spec.storageClass}}
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
  version: {{.Values.spec.eventManager.version}}
  entitlementSecret: ibm-entitlement-key
  clusterDomain: {{.Values.spec.eventManager.clusterDomain}}
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: {{.Values.spec.storageClass}}
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: {{.Values.spec.storageClass}}
    storageClassKafka: {{.Values.spec.storageClass}}
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: {{.Values.spec.storageClassLargeBlock}}
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: {{.Values.spec.storageClass}}
    storageClassCouchdb: {{.Values.spec.storageClass}}
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageSizePostgresql: 100Gi
    storageClassPostgresqlWal: {{.Values.spec.storageClass}}
    storageClassPostgresql: {{.Values.spec.storageClass}}
    storageSizePostgresqlWal: 100Gi
    storageClassCassandraData: {{.Values.spec.storageClass}}
    storageSizeCassandraData: 50Gi
    storageClassElastic: {{.Values.spec.storageClass}}
    storageClassImpactGUI: {{.Values.spec.storageClass}}
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassMinio: {{.Values.spec.storageClass}}
    storageSizeMinio: 10Gi
    storageClassNCOBackup: {{.Values.spec.storageClassLargeBlock}}
  deploymentType: {{.Values.spec.eventManager.deploymentType}}
