apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: cloud-native-postgresql-catalog-subscription
  #name: cloud-native-postgresql-stable-v1.18-ibm-operator-catalog-eventmgr1
  namespace: {{.Values.spec.eventManager.namespace}}
spec:
  channel: stable-v1.18
  installPlanApproval: Automatic
  name: cloud-native-postgresql
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
